on:
  push:
    branches:
      - master
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/release-please-action@v1.0.1
        with:
          token: ${{ secrets.pat_github }}
          release-type: node
          package-name: react-bigly-calendar
